version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - ".env"
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/market_price_watcher
      - gem_cache:/usr/local/bundle/gems

  postgres:
    image: postgres:16-alpine
    ports:
      - "5445:5432"
    env_file:
      - ".env"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  gem_cache:
  pg_data: