require 'dotenv'

require_relative 'market_price_watcher/configuration'
require_relative 'market_price_watcher/db/adapters/base'
require_relative 'market_price_watcher/db/adapters/postgresql'
require_relative 'market_price_watcher/db/migrator'
require_relative 'market_price_watcher/network/connection'
require_relative 'market_price_watcher/repositories/repositories'
require_relative 'market_price_watcher/scrapers/scrapers'
require_relative 'market_price_watcher/scraper_factory'
require_relative 'market_price_watcher/utils/utils'
require_relative 'market_price_watcher/keyboards/keyboards'
require_relative 'market_price_watcher/actions/actions'
require_relative 'market_price_watcher/workers/product_tracker'
require_relative 'market_price_watcher/handlers/handlers'
require_relative 'market_price_watcher/scheduler'
require_relative 'market_price_watcher/runner'
